In [1]:
import pandas as pd
import numpy as np

In [ ]:
data = pd.Series([1, 2, 3, 4], index=['a', 'b', 'c', 'd'])
print(data)

a    1
b    2
c    3
d    4
dtype: int64

In [ ]:
population_dict = {'California' : 78198682,
                   'Texas' : 27299277,
                   'New York' : 92895229,
                   'Florida' : 195554271,
                   'Illiones' : 122294258 }
population = pd.Series(population_dict)
population

California     78198682
Texas          27299277
New York       92895229
Florida       195554271
Illiones      122294258
dtype: int64

In [ ]:
print(population['California'])
print(population['California':'Illiones'])

78198682
California     78198682
Texas          27299277
New York       92895229
Florida       195554271
Illiones      122294258
dtype: int64

In [ ]:
pd.Series({'a': 2, 'c' : 5, 'b' : 10}, index = ['a', 'c'])

a    2
c    5
dtype: int64

In [ ]:
data = [{'a' : i, 'b' : i * 2} for i in range(3)]
pd.DataFrame(data)

   a  b
0  0  0
1  1  2
2  2  4

In [ ]:
data2 = [{'a' : 2, 'b' : 4}, {'a' : 6, 'c' : 55}, {'b' : 5, 'c' : 6}]
pd.DataFrame(data2)

     a    b     c
0  2.0  4.0   NaN
1  6.0  NaN  55.0
2  NaN  5.0   6.0

In [ ]:
pd.DataFrame(np.random.rand(3, 2), columns = ['foo', 'bar'], index = ['a', 'b', 'c'])

        foo       bar
a  0.149459  0.780156
b  0.129540  0.072511
c  0.103787  0.964877

In [16]:
pd.DataFrame(population, columns=['population'])

            population
California    78198682
Texas         27299277
New York      92895229
Florida      195554271
Illiones     122294258

In [15]:
population_dict = {'California' : 78198682,
                   'Texas' : 27299277,
                   'New York' : 92895229,
                   'Florida' : 195554271,
                   'Illiones' : 122294258 
                }
area_dict = {'California': 423967, 
             'Texas': 695662, 
             'New York': 141297,
             'Florida': 170312, 
             'Illiones': 149995
            }
population = pd.Series(population_dict)
area = pd.Series(area_dict)

states = pd.DataFrame({'population' : population, 'area' : area})

states

            population    area
California    78198682  423967
Texas         27299277  695662
New York      92895229  141297
Florida      195554271  170312
Illiones     122294258  149995

In [33]:
num = pd.Series([1, 2, 3])
print(num + 5)

0    6
1    7
2    8
dtype: int64

In [37]:
s1 = pd.Series([1,3], index = ['a', 'b'])
s2 = pd.Series([2,9], index = ['b', 'c'])
print(s1 + s2)

a    NaN
b    5.0
c    NaN
dtype: float64

In [17]:
df = pd.DataFrame({
    "Age" : [18, 20],
    "Score" : [15, 22]
})
print(df + 2)
print("------------")
print(df["Age"] + 2)
print("------------")
print(df["Score"] > 20)
print("------------")
print(df[df["Age"] > 18])

   Age  Score
0   20     17
1   22     24
------------
0    20
1    22
Name: Age, dtype: int64
------------
0    False
1     True
Name: Score, dtype: bool
------------
   Age  Score
1   20     22

In [ ]:
df['Results']  = df['Score'] * 2
print(df)

   Age  Score  Results
0   18     15       30
1   20     22       44

             Age      Score    Results
count   2.000000   2.000000   2.000000
mean   19.000000  18.500000  37.000000
std     1.414214   4.949747   9.899495
min    18.000000  15.000000  30.000000
25%    18.500000  16.750000  33.500000
50%    19.000000  18.500000  37.000000
75%    19.500000  20.250000  40.500000
max    20.000000  22.000000  44.000000

In [41]:
s1 = pd.Series([1,3], index = ['a', 'b'])
s2 = pd.Series([2,9], index = ['b', 'c'])
s3 = s1 + s2
s3.isna()

a     True
b    False
c     True
dtype: bool